---
language: c
matrix:
  include:
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode7.3
before_script:
  - rvm get head || true
script:
  - brew update >/dev/null
  - brew install emacs.rb --with-cocoa --HEAD --verbose || true
