---
language: c
matrix:
  include:
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: beta-xcode6.2
compiler: gcc
script:
  - brew update
  - brew install emacs.rb --with-cocoa --HEAD --verbose
